# Generated by Django 4.0.4 on 2022-07-17 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='bike_images')),
                ('bike_manufacturer', models.CharField(max_length=20)),
                ('bike_model', models.PositiveIntegerField(default=0)),
                ('bike_price', models.PositiveIntegerField()),
                ('bike_km', models.PositiveIntegerField(null=True)),
                ('bike_capacity', models.FloatField(null=True)),
                ('bike_description', models.CharField(max_length=40)),
                ('owner_type', models.CharField(choices=[('First owner', 'First owner'), ('Second owner', 'Second owner'), ('Third owner', 'Third owner')], max_length=20)),
                ('address', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('added_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, null=True)),
                ('profile_image', models.ImageField(upload_to='profile_pic')),
                ('user_address', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterestedBikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Sold', 'Sold')], max_length=25)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='bikeusers.bikes')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BikeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bike_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bikes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikemdl', to='bikeusers.bikes')),
            ],
        ),
    ]
