# Generated by Django 4.0.4 on 2022-07-18 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bikeusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestedbikes',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bike_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bikeimages',
            name='image',
            field=models.ImageField(null=True, upload_to='bike_images'),
        ),
        migrations.AlterField(
            model_name='interestedbikes',
            name='status',
            field=models.CharField(choices=[('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Sold', 'Sold'), ('Rejected', 'Rejected')], max_length=25),
        ),
    ]
